language: erlang
notifications:
  recipients:
    - jordan+travis-booter@jordan.io
otp_release:
  - 17.0
before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir
  - git checkout v1.0
  - make && cd ..
before_script: "export PATH=`pwd`/elixir/bin:$PATH"
script: "mix do local.hex --force, deps.get && mix test"

